### PR TITLE
Fix updating DataView length when backing buffer is resized

### LINKED ISSUE #988: setUint8 throws when ArrayBuffer is resizable
This should work

```
import * as std from "qjs:std";
import * as os from "qjs:os";

const buffer = new ArrayBuffer(0, {maxByteLength: 16384});
const view = new DataView(buffer);
const arr = [97, 98, 99];
const file = os.open("test.txt", os.O_RDWR | os.O_CREAT | os.O_TRUNC, 0o764);
buffer.resize(arr.length);
console.log(buffer.byteLength);
for (let i = 0; i < arr.length; i++) {
  console.log(`setUint8(${i}, ${arr[i]})`);
  view.setUint8(i, arr[i]);
}
console.log(os.write(file, buffer, 0, buffer.byteLength));
console.log(os.close(file));
```

I get 

```
3
setUint8(0, 97)
Possibly unhandled promise rejection: RangeError: out of bound
    at setUint8 (native)
    at <anonymous> (test.js:15:17)
```

Looks like a bug in `DataView` reading resizable `ArrayBuffer`.

This works as expected

```
import * as std from "qjs:std";
import * as os from "qjs:os";

const buffer = new ArrayBuffer(3);
const view = new DataView(buffer);
const arr = [97, 98, 99];
const file = os.open("test.txt", os.O_RDWR | os.O_CREAT | os.O_TRUNC, 0o764);
//buffer.resize(arr.length);
console.log(buffer.byteLength);
for (let i = 0; i < arr.length; i++) {
  console.log(`setUint8(${i}, ${arr[i]})`);
  view.setUint8(i, arr[i]);
}
console.log(os.write(file, buffer, 0, buffer.byteLength));
console.log(os.close(file));
```

```
3
setUint8(0, 97)
setUint8(1, 98)
setUint8(2, 99)
3
0
```

```
ls -l test.txt
-rwxr--r-- 1 user user 3 Mar 20 05:09 test.txt
```

### PR DESCRIPTION
**Pull request by saghul**
Fixes: https://github.com/quickjs-ng/quickjs/issues/988

### CODE REVIEW

**Comment by saghul** [comment]
Somewhat surprised 262 didn't catch this. Am I being too naive or is this it?

**Comment by bnoordhuis** [comment]
Yours might be the better fix but I took a different approach in #989 because the ECMA spec language is woolly enough that I'm not sure if what you're doing here is legal.

And no, there are no test262 tests that cover this (or at least, I haven't been able to find them.)

**Comment by saghul** [comment]
Interesting!

If i'm reading this right, with your PR the `byteLength` won't be updated, right? V8 / JSC seem to update it, when checking with Node / Bun.

**Comment by bnoordhuis** [comment]
Yeah, and updating is sensible behavior, but common sense never stopped TC39 before, so :shrug:

Note how your change breaks a number of DataView tests, although maybe that's simply because they expect RangeErrors instead of a TypeErrors, or vice versa.

**Comment by saghul** [comment]
What's your take? I don't have a strong opinion :-) If you think yours is the better fix I'm happy to close this.

**Comment by bnoordhuis** [comment]
If you can get the tests to pass, your way is probably better. Aligning with what other engines do would be good.

**Comment by saghul** [comment]
Alright, I'll give that a try!

**Comment by saghul** [comment]
I think I got it. The problem is we need to differentiate between the `AUTO` byte length and the non-auto case in order to adjust it: https://tc39.es/ecma262/multipage/structured-data.html#sec-dataview-constructor

We currently don't, and updating the length will be dependent on that.

I'll try to get it fixed tonight.

**Comment by saghul** [comment]
@bnoordhuis Updated, PTAL! I also incorporated your test.

File: tests/bug988.js [hunk 1]
```diff
@@ -0,0 +1,8 @@
+import {assert} from  "./assert.js"
+const expected = [97,98,99]
+const ab = new ArrayBuffer(0, {maxByteLength:3})
+const dv = new DataView(ab)
+ab.resize(3)
+for (const [i,v] of Object.entries(expected)) dv.setUint8(i, v)
+for (const [i,v] of Object.entries(expected)) assert(v, dv.getUint8(i))
+
```
Comment (bnoordhuis) [inline tests/bug988.js]:
```suggestion
```
I'm sure I didn't leave that blank line there :)

**Review by bnoordhuis — APPROVED** [review]
