### PR TITLE
Port recent OOM-handling and memory leak fixes from bellard/quickjs

### LINKED ISSUE #1066: More robust out of memory handling (bellard)
From a first (very) quick glance, it looks like a number of the fixes here could apply: https://github.com/bellard/quickjs/commit/3dc7ef1f7f500e39698bef9762b904b2690bb369

### PR DESCRIPTION
**Pull request by past-due**
Fixes #1066

Ports:
https://github.com/bellard/quickjs/commit/db3d3f09cdec7106d6e330aa1eb3fae50ed8fdc4
https://github.com/bellard/quickjs/commit/3dc7ef1f7f500e39698bef9762b904b2690bb369 (except changes to build_backtrace)

### CODE REVIEW

File: quickjs.c [hunk 1]
```diff
@@ -6959,9 +6963,10 @@ static JSValue JS_MakeError(JSContext *ctx, JSErrorEnum error_num,
     if (!JS_IsException(msg)) {
         JS_DefinePropertyValue(ctx, obj, JS_ATOM_message, msg,
                                JS_PROP_WRITABLE | JS_PROP_CONFIGURABLE);
+    
+        if (add_backtrace)
+            build_backtrace(ctx, obj, JS_UNDEFINED, NULL, 0, 0, 0);
     }
-    if (add_backtrace)
-        build_backtrace(ctx, obj, JS_UNDEFINED, NULL, 0, 0, 0);
```
Comment (bnoordhuis) [inline quickjs.c]: This change looks kind of dubious to me. _Ceteris paribus_, it's better to have a backtrace.

**Review by bnoordhuis — COMMENTED** [review]
One comment, otherwise LGTM.

File: quickjs.c (hunk 1 above)
Comment (past-due) [reply quickjs.c]: I believe the reason this was part of the upstream commit is that all but one (?) of the reasons `JS_NewString` (`JS_NewStringLen`) might fail are due to an allocation / OOM situation.

EDIT: And since the case of an invalid message is already handled above:
```
    msg = JS_NewString(ctx, message);
    if (JS_IsException(msg))
        msg = JS_NewString(ctx, "Invalid error message");
```
The _only_ case where `msg` is still an exception at this point should be if `JS_NewStringLen` failed due to allocation failure (OOM). Avoiding the call to build_backtrace in this case seems reasonable (it looks like it tries to allocate plenty of things itself)?

Comment (bnoordhuis) [reply quickjs.c]: My thinking is that it's better to try and fail than not try at all, so can you move it outside the block again?

Comment (past-due) [reply quickjs.c]: > My thinking is that it's better to try and fail than not try at all, so can you move it outside the block again?

Done. 👍

Of note: Since it has diverged from bellard/quickjs, I did not fully audit `build_backtrace` to ensure it properly handles all memory allocation failures internally - would be worth looking at in the future.

**Review by bnoordhuis — APPROVED** [review]
