### PR TITLE
Fix exporting destructured variables

### LINKED ISSUE #382: exporting destructured variables fails
minimal repro:
```sh
~ $ cat a.mjs
import * as mod from "./a.mjs"
export const { a, b, c } = { a: 1, b: 2, c: 3 };  export const d = 4;
console.log(JSON.stringify({                        type: typeof mod,
  keys: Object.keys(mod),
}));
~ $ node a.mjs
{"type":"object","keys":["a","b","c","d"]}
~ $ qjs -m a.mjs
{"type":"object","keys":["d"]}
~ $
```

### PR DESCRIPTION
**Pull request by saghul**
Fixes: https://github.com/bellard/quickjs/issues/382

### CODE REVIEW

**Comment by saghul** [comment]
@bnoordhuis PTAL, this is my first foray into the parser 😅

File: quickjs.c [hunk 1]
```diff
@@ -23009,7 +23009,7 @@ static JSAtom js_parse_destructuring_var(JSParseState *s, int tok, int is_arg)
    present at the top level. */
 static int js_parse_destructuring_element(JSParseState *s, int tok, int is_arg,
                                         int hasval, int has_ellipsis,
-                                        bool allow_initializer)
+                                        bool allow_initializer, bool export_flag)
```
Comment (bnoordhuis) [inline quickjs.c:23012]: A suggestion for a follow-up PR: replace these 5 booleans with a flags argument. Call sites are IMO more legible as `frob(HasArg|HasVal|HasEllipsis|AllowInitializer|ExportFlag)` than `frob(true,false,false,true,true)`

(I suppose that, although its name suggests it's a boolean, has_ellipsis is actually a tri-state. The others are booleans though.)

**Review by bnoordhuis — APPROVED** [review]

File: quickjs.c (hunk 1 above)
Comment (saghul) [reply quickjs.c:23012]: Good idea, will do!
