### PR TITLE
Report async failures via exit code

### LINKED ISSUE #340: qjs/std should report async failures via exit code
Example: assert triggered from timer callback should exit with a non-zero error but doesn't. quickjs-libc.c calls `js_std_dump_error()` and trucks on.
```
$ build/qjs tests/test_std.js
Error: assertion failed: got |false|, expected |true|
    at assert (tests/test_std.js:21:51)
    at d (tests/test_std.js:287:33)

$ echo $?
0
```
_Originally posted by @saghul in https://github.com/quickjs-ng/quickjs/issues/338#issuecomment-2032266845_

### PR DESCRIPTION
**Pull request by saghul**
Fixes: https://github.com/quickjs-ng/quickjs/issues/340

### CODE REVIEW

**Comment by saghul** [comment]
Comes after https://github.com/quickjs-ng/quickjs/pull/513

**Comment by saghul** [comment]
```
 Error: assertion failed: got |false|, expected |true|
    at assert (tests/test_std.js:21:51)
    at d (tests/test_std.js:289:33)

make: *** [test] Error 1
```

Ha, looks like the PR works :-P

File: quickjs-libc.c [hunk 1]
```diff
@@ -2171,9 +2180,9 @@ static int js_os_run_timers(JSRuntime *rt, JSContext *ctx, JSThreadState *ts)
                 th->timeout = cur_time + th->delay;
             else
                 free_timer(rt, th);
-            call_handler(ctx, func);
+            r = call_handler(ctx, func);
             JS_FreeValueRT(rt, func);
-            return 0;
+            return r;
```
Comment (bnoordhuis) [inline quickjs-libc.c:2187]: Rather than making callers check for an out-of-band `JS_IsException(ts->exc)` (easy to forget), it's more robust and (arguably) idiomatic to turn min_delay into an out param and make js_os_run_timers return 0 or -1.

**Comment by saghul** [comment]
Greeeeen! @bnoordhuis PTAL!

**Review by bnoordhuis — APPROVED** [review]
LGTM with a suggestion.

File: quickjs-libc.c (hunk 1 above)
Comment (saghul) [reply quickjs-libc.c:2187]: Cna do!

**Comment by saghul** [comment]
Done! I also initialized min_delay to INT32_MAX, 10000 looked very arbitrary.
