### PR TITLE
Make quickjs.h -Wall -Wextra -pedantic clean

### LINKED ISSUE #585: Compilation in C++ fails when -Wpedantic and -Werror=unused-parameter flags are used
I am compiling the library with relaxed flags but I have stricter flags on my C++ code. And because my code includes quickjs.h I get the errors below

```
_deps/quickjs-ng-src/quickjs.h: In function ‘JSValue JS_NewBool(JSContext*, int)’:
_deps/quickjs-ng-src/quickjs.h:181:68: error: ISO C++ forbids compound-literals [-Wpedantic]
  181 | #define JS_MKVAL(tag, val) (JSValue){ (JSValueUnion){ .int32 = val }, tag }
      |                                                                    ^
_deps/quickjs-ng-src/quickjs.h:483:12: note: in expansion of macro ‘JS_MKVAL’
  483 |     return JS_MKVAL(JS_TAG_BOOL, (val != 0));
      |            ^~~~~~~~
_deps/quickjs-ng-src/quickjs.h:181:75: error: ISO C++ forbids compound-literals [-Wpedantic]
  181 | #define JS_MKVAL(tag, val) (JSValue){ (JSValueUnion){ .int32 = val }, tag }
      |                                                                           ^
_deps/quickjs-ng-src/quickjs.h:483:12: note: in expansion of macro ‘JS_MKVAL’
  483 |     return JS_MKVAL(JS_TAG_BOOL, (val != 0));
      |            ^~~~~~~~
_deps/quickjs-ng-src/quickjs.h:481:54: error: unused parameter ‘ctx’ [-Werror=unused-parameter]
  481 | static js_force_inline JSValue JS_NewBool(JSContext *ctx, JS_BOOL val)
      |                                           ~~~~~~~~~~~^~~
_deps/quickjs-ng-src/quickjs.h: In function ‘JSValue JS_NewInt32(JSContext*, int32_t)’:
_deps/quickjs-ng-src/quickjs.h:181:68: error: ISO C++ forbids compound-literals [-Wpedantic]
  181 | #define JS_MKVAL(tag, val) (JSValue){ (JSValueUnion){ .int32 = val }, tag }
      |                                                                    ^
_deps/quickjs-ng-src/quickjs.h:488:12: note: in expansion of macro ‘JS_MKVAL’
  488 |     return JS_MKVAL(JS_TAG_INT, val);
      |            ^~~~~~~~
_deps/quickjs-ng-src/quickjs.h:181:75: error: ISO C++ forbids compound-literals [-Wpedantic]
  181 | #define JS_MKVAL(tag, val) (JSValue){ (JSValueUnion){ .int32 = val }, tag }
      |                                                                           ^
_deps/quickjs-ng-src/quickjs.h:488:12: note: in expansion of macro ‘JS_MKVAL’
  488 |     return JS_MKVAL(JS_TAG_INT, val);
      |            ^~~~~~~~
_deps/quickjs-ng-src/quickjs.h:486:55: error: unused parameter ‘ctx’ [-Werror=unused-parameter]
  486 | static js_force_inline JSValue JS_NewInt32(JSContext *ctx, int32_t val)
      |                                            ~~~~~~~~~~~^~~
_deps/quickjs-ng-src/quickjs.h: In function ‘JSValue JS_NewFloat64(JSContext*, double)’:
_deps/quickjs-ng-src/quickjs.h:491:57: error: unused parameter ‘ctx’ [-Werror=unused-parameter]
  491 | static js_force_inline JSValue JS_NewFloat64(JSContext *ctx, double val)
      |                                              ~~~~~~~~~~~^~~
_deps/quickjs-ng-src/quickjs.h: In function ‘JSValue JS_NewCatchOffset(JSContext*, int32_t)’:
_deps/quickjs-ng-src/quickjs.h:181:68: error: ISO C++ forbids compound-literals [-Wpedantic]
  181 | #define JS_MKVAL(tag, val) (JSValue){ (JSValueUnion){ .int32 = val }, tag }
      |                                                                    ^
_deps/quickjs-ng-src/quickjs.h:498:12: note: in expansion of macro ‘JS_MKVAL’
  498 |     return JS_MKVAL(JS_TAG_CATCH_OFFSET, val);
      |            ^~~~~~~~
_deps/quickjs-ng-src/quickjs.h:181:75: error: ISO C++ forbids compound-literals [-Wpedantic]
  181 | #define JS_MKVAL(tag, val) (JSValue){ (JSValueUnion){ .int32 = val }, tag }
      |                                                                           ^
_deps/quickjs-ng-src/quickjs.h:498:12: note: in expansion of macro ‘JS_MKVAL’
  498 |     return JS_MKVAL(JS_TAG_CATCH_OFFSET, val);
      |            ^~~~~~~~
_deps/quickjs-ng-src/quickjs.h:496:61: error: unused parameter ‘ctx’ [-Werror=unused-parameter]
  496 | static js_force_inline JSValue JS_NewCatchOffset(JSContext *ctx, int32_t val)
      |                                                  ~~~~~~~~~~~^~~
_deps/quickjs-ng-src/quickjs.h: In function ‘int JS_IsBigInt(JSContext*, JSValue)’:
_deps/quickjs-ng-src/quickjs.h:533:46: error: unused parameter ‘ctx’ [-Werror=unused-parameter]
  533 | static inline JS_BOOL JS_IsBigInt(JSContext *ctx, JSValue v)
      |                                   ~~~~~~~~~~~^~~
_deps/quickjs-ng-src/quickjs.h: In function ‘JSValue JS_DupValue(JSContext*, JSValue)’:
_deps/quickjs-ng-src/quickjs.h:614:46: error: unused parameter ‘ctx’ [-Werror=unused-parameter]
  614 | static inline JSValue JS_DupValue(JSContext *ctx, JSValue v)
      |                                   ~~~~~~~~~~~^~~
_deps/quickjs-ng-src/quickjs.h: In function ‘JSValue JS_DupValueRT(JSRuntime*, JSValue)’:
_deps/quickjs-ng-src/quickjs.h:623:48: error: unused parameter ‘rt’ [-Werror=unused-parameter]
  623 | static inline JSValue JS_DupValueRT(JSRuntime *rt, JSValue v)
```

### PR DESCRIPTION
**Pull request by bnoordhuis**
Fixes: https://github.com/quickjs-ng/quickjs/issues/585

### CODE REVIEW

File: quickjs.h [hunk 1]
```diff
@@ -514,21 +514,25 @@ JS_EXTERN int JS_IsRegisteredClass(JSRuntime *rt, JSClassID class_id);
 
 static js_force_inline JSValue JS_NewBool(JSContext *ctx, JS_BOOL val)
 {
+    (void)&ctx;
```
Comment (saghul) [inline quickjs.h:517]: Is the & necessary? I thought (void)ctx; would be enough.

**Review by saghul — APPROVED** [review]

File: quickjs.h (hunk 1 above)
Comment (bnoordhuis) [reply quickjs.h:517]: It's not necessary here but it's a general precaution, in case the unused thing is a macro that evaluates to something non-addressable (because that probably indicates dead code, or a bug.)

Comment (saghul) [reply quickjs.h:517]: TIL!
