### PR TITLE
Run FinalizationRegistry callback in the job queue

### LINKED ISSUE #432: Heap-use-after-free in delete_finrec_weakref
###### Commit ID
b09ad82622fe083af51f736ea73f9f6728562f1c

###### Build platform
Ubuntu 22.04.3

###### Build steps
```sh
cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCONFIG_ASAN=ON -DCMAKE_BUILD_TYPE=Debug
cmake --build . -j $(nproc)
```

###### Test case
```sh
function main() {
    const registry = new FinalizationRegistry(() => { console.log(console = main()) });
    const token = { a: "v8" };
    registry.register(token, console => {});
    registry.register([]);
    return registry;
}
main();
```

###### Execution steps
```sh
./qjs poc.js
```

###### Output
```sh
[object FinalizationRegistry]
=================================================================
==2142064==ERROR: AddressSanitizer: heap-use-after-free on address 0x607000158708 at pc 0x561f729e42a8 bp 0x7fffbdec3890 sp 0x7fffbdec3880
READ of size 8 at 0x607000158708 thread T0
    #0 0x561f729e42a7 in delete_finrec_weakref /quickjs-ng/quickjs.c:52639
    #1 0x561f729e4535 in js_finrec_finalizer /quickjs-ng/quickjs.c:52658
    #2 0x561f7282e506 in free_object /quickjs-ng/quickjs.c:5404
    #3 0x561f7282e7b3 in free_gc_object /quickjs-ng/quickjs.c:5424
    #4 0x561f7282e9a0 in free_zero_refcount /quickjs-ng/quickjs.c:5446
    #5 0x561f7282ed71 in __JS_FreeValueRT /quickjs-ng/quickjs.c:5494
    #6 0x561f7282efa5 in __JS_FreeValue /quickjs-ng/quickjs.c:5523
    #7 0x561f7280b923 in JS_FreeValue /quickjs-ng/quickjs.h:602
    #8 0x561f728a37d9 in JS_CallInternal /quickjs-ng/quickjs.c:17092
    #9 0x561f728a3e52 in JS_Call /quickjs-ng/quickjs.c:17135
    #10 0x561f729e67e0 in reset_weak_ref /quickjs-ng/quickjs.c:52871
    #11 0x561f7282e406 in free_object /quickjs-ng/quickjs.c:5399
    #12 0x561f7282e7b3 in free_gc_object /quickjs-ng/quickjs.c:5424
    #13 0x561f7282e9a0 in free_zero_refcount /quickjs-ng/quickjs.c:5446
    #14 0x561f7282ed71 in __JS_FreeValueRT /quickjs-ng/quickjs.c:5494
    #15 0x561f7282efa5 in __JS_FreeValue /quickjs-ng/quickjs.c:5523
    #16 0x561f7280b923 in JS_FreeValue /quickjs-ng/quickjs.h:602
    #17 0x561f728a3c68 in JS_CallInternal /quickjs-ng/quickjs.c:17125
    #18 0x561f72888635 in JS_CallInternal /quickjs-ng/quickjs.c:15012
    #19 0x561f728a3f60 in JS_CallFree /quickjs-ng/quickjs.c:17142
    #20 0x561f72927aff in JS_EvalFunctionInternal /quickjs-ng/quickjs.c:32786
    #21 0x561f72928f90 in __JS_EvalInternal /quickjs-ng/quickjs.c:32920
    #22 0x561f729291f7 in JS_EvalInternal /quickjs-ng/quickjs.c:32938
    #23 0x561f72929659 in JS_EvalThis /quickjs-ng/quickjs.c:32969
    #24 0x561f7292974b in JS_Eval /quickjs-ng/quickjs.c:32977
    #25 0x561f727dcf23 in eval_buf /quickjs-ng/qjs.c:63
    #26 0x561f727dd2ae in eval_file /quickjs-ng/qjs.c:95
    #27 0x561f727dffdc in main /quickjs-ng/qjs.c:519
    #28 0x7f9996fcf082 in __libc_start_main ../csu/libc-start.c:308
    #29 0x561f727dc87d in _start (/quickjs-ng/qjs+0xd387d)

0x607000158708 is located 40 bytes inside of 72-byte region [0x6070001586e0,0x607000158728)
freed by thread T0 here:
    #0 0x7f999742240f in __interceptor_free ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:122
    #1 0x561f7280f324 in js_def_free /quickjs-ng/quickjs.c:1717
    #2 0x561f7280d361 in js_free_rt /quickjs-ng/quickjs.c:1383
    #3 0x561f72830c24 in gc_free_cycles /quickjs-ng/quickjs.c:5773
    #4 0x561f72830d14 in JS_RunGC /quickjs-ng/quickjs.c:5789
    #5 0x561f7280d1dc in js_trigger_gc /quickjs-ng/quickjs.c:1365
    #6 0x561f72828bcd in JS_NewObjectFromShape /quickjs-ng/quickjs.c:4714
    #7 0x561f728298aa in JS_NewObjectProtoClass /quickjs-ng/quickjs.c:4833
    #8 0x561f72839d8e in JS_ThrowError2 /quickjs-ng/quickjs.c:6621
    #9 0x561f7283a273 in JS_ThrowError /quickjs-ng/quickjs.c:6653
    #10 0x561f7283a811 in JS_ThrowTypeError /quickjs-ng/quickjs.c:6684
    #11 0x561f72881ead in JS_CallInternal /quickjs-ng/quickjs.c:14634
    #12 0x561f72888db7 in JS_CallInternal /quickjs-ng/quickjs.c:15048
    #13 0x561f728a3e52 in JS_Call /quickjs-ng/quickjs.c:17135
    #14 0x561f729e67e0 in reset_weak_ref /quickjs-ng/quickjs.c:52871
    #15 0x561f7282e406 in free_object /quickjs-ng/quickjs.c:5399
    #16 0x561f7282e7b3 in free_gc_object /quickjs-ng/quickjs.c:5424
    #17 0x561f7282e9a0 in free_zero_refcount /quickjs-ng/quickjs.c:5446
    #18 0x561f7282ed71 in __JS_FreeValueRT /quickjs-ng/quickjs.c:5494
    #19 0x561f7282efa5 in __JS_FreeValue /quickjs-ng/quickjs.c:5523
    #20 0x561f7280b923 in JS_FreeValue /quickjs-ng/quickjs.h:602
    #21 0x561f728a3c68 in JS_CallInternal /quickjs-ng/quickjs.c:17125
    #22 0x561f72888635 in JS_CallInternal /quickjs-ng/quickjs.c:15012
    #23 0x561f728a3f60 in JS_CallFree /quickjs-ng/quickjs.c:17142
    #24 0x561f72927aff in JS_EvalFunctionInternal /quickjs-ng/quickjs.c:32786
    #25 0x561f72928f90 in __JS_EvalInternal /quickjs-ng/quickjs.c:32920
    #26 0x561f729291f7 in JS_EvalInternal /quickjs-ng/quickjs.c:32938
    #27 0x561f72929659 in JS_EvalThis /quickjs-ng/quickjs.c:32969
    #28 0x561f7292974b in JS_Eval /quickjs-ng/quickjs.c:32977
    #29 0x561f727dcf23 in eval_buf /quickjs-ng/qjs.c:63

previously allocated by thread T0 here:
    #0 0x7f9997422808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x561f7280f189 in js_def_malloc /quickjs-ng/quickjs.c:1701
    #2 0x561f7280d2e6 in js_malloc_rt /quickjs-ng/quickjs.c:1378
    #3 0x561f7280d5ab in js_malloc /quickjs-ng/quickjs.c:1416
    #4 0x561f72828bf0 in JS_NewObjectFromShape /quickjs-ng/quickjs.c:4715
    #5 0x561f72829db2 in JS_NewArray /quickjs-ng/quickjs.c:4872
    #6 0x561f72889081 in JS_CallInternal /quickjs-ng/quickjs.c:15066
    #7 0x561f72888635 in JS_CallInternal /quickjs-ng/quickjs.c:15012
    #8 0x561f728a3e52 in JS_Call /quickjs-ng/quickjs.c:17135
    #9 0x561f729e67e0 in reset_weak_ref /quickjs-ng/quickjs.c:52871
    #10 0x561f7282e406 in free_object /quickjs-ng/quickjs.c:5399
    #11 0x561f7282e7b3 in free_gc_object /quickjs-ng/quickjs.c:5424
    #12 0x561f7282e9a0 in free_zero_refcount /quickjs-ng/quickjs.c:5446
    #13 0x561f7282ed71 in __JS_FreeValueRT /quickjs-ng/quickjs.c:5494
    #14 0x561f7282efa5 in __JS_FreeValue /quickjs-ng/quickjs.c:5523
    #15 0x561f7280b923 in JS_FreeValue /quickjs-ng/quickjs.h:602
    #16 0x561f728a3c68 in JS_CallInternal /quickjs-ng/quickjs.c:17125
    #17 0x561f72888635 in JS_CallInternal /quickjs-ng/quickjs.c:15012
    #18 0x561f728a3f60 in JS_CallFree /quickjs-ng/quickjs.c:17142
    #19 0x561f72927aff in JS_EvalFunctionInternal /quickjs-ng/quickjs.c:32786
    #20 0x561f72928f90 in __JS_EvalInternal /quickjs-ng/quickjs.c:32920
    #21 0x561f729291f7 in JS_EvalInternal /quickjs-ng/quickjs.c:32938
    #22 0x561f72929659 in JS_EvalThis /quickjs-ng/quickjs.c:32969
    #23 0x561f7292974b in JS_Eval /quickjs-ng/quickjs.c:32977
    #24 0x561f727dcf23 in eval_buf /quickjs-ng/qjs.c:63
    #25 0x561f727dd2ae in eval_file /quickjs-ng/qjs.c:95
    #26 0x561f727dffdc in main /quickjs-ng/qjs.c:519
    #27 0x7f9996fcf082 in __libc_start_main ../csu/libc-start.c:308

SUMMARY: AddressSanitizer: heap-use-after-free /quickjs-ng/quickjs.c:52639 in delete_finrec_weakref
Shadow bytes around the buggy address:
  0x0c0e80023090: fd fa fa fa fa fa 00 00 00 00 00 00 00 00 00 fa
  0x0c0e800230a0: fa fa fa fa 00 00 00 00 00 00 00 00 00 fa fa fa
  0x0c0e800230b0: fa fa fd fd fd fd fd fd fd fd fd fa fa fa fa fa
  0x0c0e800230c0: 00 00 00 00 00 00 00 00 00 fa fa fa fa fa 00 00
  0x0c0e800230d0: 00 00 00 00 00 00 00 00 fa fa fa fa fd fd fd fd
=>0x0c0e800230e0: fd[fd]fd fd fd fa fa fa fa fa 00 00 00 00 00 00
  0x0c0e800230f0: 00 00 00 00 fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c0e80023100: fd fa fa fa fa fa 00 00 00 00 00 00 00 00 00 fa
  0x0c0e80023110: fa fa fa fa 00 00 00 00 00 00 00 00 00 fa fa fa
  0x0c0e80023120: fa fa fd fd fd fd fd fd fd fd fd fa fa fa fa fa
  0x0c0e80023130: 00 00 00 00 00 00 00 00 00 fa fa fa fa fa 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==2142064==ABORTING

```

### PR DESCRIPTION
**Pull request by saghul**
The spec says HostMakeJobCallback has to be used on the callback: https://tc39.es/ecma262/multipage/managing-memory.html#sec-finalization-registry-cleanup-callback

That makes the following (arguably contrived) example run forever until memory is exhausted.

```js
let count = 0;
function main() {
    console.log(`main! ${++count}`);
    const registry = new FinalizationRegistry(() => {
        globalThis.foo = main();
    });
    registry.register([]);
    registry.register([]);
    return registry;
}
main();

console.log(count);
```

That is unlike V8, which runs 0 times. This can be explained by the difference in GC implementations and since FinRec makes GC observable, here we are!

Fixes: https://github.com/quickjs-ng/quickjs/issues/432

### CODE REVIEW

File: tests/test_builtin.js [hunk 1]
```diff
@@ -997,15 +997,19 @@ function test_finalization_registry()
     {
         let expected = {};
         let actual;
-        let finrec = new FinalizationRegistry(v => { actual = v });
-        finrec.register({}, expected); // {} goes out of scope immediately
-        assert(actual, expected);
+        let finrec = new FinalizationRegistry(v => { 
+            actual = v;
+            assert(actual, expected);
```
Comment (bnoordhuis) [inline tests/test_builtin.js:1003]: This weakens the test because the assert won't run when the bug it tests for is reintroduced.

Node's test suite has a `mustCall()` method but it's implemented in terms of `process.on("exit")` and qjs doesn't have that, of course. Maybe you can sort of fake it with a `setTimeout()` but that might be flaky.

(As an aside: it's no longer necessary to have the `let actual` at the top; rename the parameter to `actual` and done)

Comment (saghul) [reply tests/test_builtin.js:1003]: We have queueMicrotask, maybe a check there is good.

**Comment by saghul** [comment]
@bnoordhuis THis one should be ready now. I had to dig deep, so pl let me know what you think!

File: quickjs.c [hunk 2]
```diff
@@ -1812,6 +1814,9 @@ int JS_EnqueueJob(JSContext *ctx, JSJobFunc *job_func,
     JSJobEntry *e;
     int i;
 
+    if (rt->in_free)
+        return -1;
```
Comment (bnoordhuis) [inline quickjs.c:1818]: This is going to result in leaking the argv if the caller doesn't check the return code. Which we don't in many places, and where we do, we expect an exception to have been raised.

Comment (saghul) [reply quickjs.c:1818]: Not really because enqueue dups the arguments, so the caller doesn't dup them.

Comment (saghul) [reply quickjs.c:1818]: You could indeed argue there is no exception raised, but since this happens in such a weird spot, I thought I'd just get away with it :-P

Comment (saghul) [reply quickjs.c:1818]: Alternatively, I could check if `rt->in_free` when resetting the weakref, and just avoid the whole thing, but calling JS_EnqueueJob when the runtime is going away still leads to leaks.

Comment (bnoordhuis) [reply quickjs.c:1818]: I'd probably scope it narrowly to reset_weak_ref() and maybe add an assert to JS_EnqueueJob() because it's probably always a bug if you call that when tearing down the runtime.

Comment (saghul) [reply quickjs.c:1818]: Can do!

Comment (saghul) [reply quickjs.c:1818]: Updated!

**Review by bnoordhuis — APPROVED** [review]
:+1:

File: quickjs.c [hunk 3]
```diff
@@ -53310,12 +53322,11 @@ static void reset_weak_ref(JSRuntime *rt, JSWeakRefRecord **first_weak_ref)
...
-                JS_FreeValueRT(rt, ret);
-                JS_FreeValueRT(rt, fre->held_val);
+            if (!rt->in_free && (!JS_IsObject(fre->held_val) || JS_IsLiveObject(rt, fre->held_val))) {
+                JSValue args[2];
+                args[0] = frd->cb;
+                args[1] = fre->held_val;
+                JS_EnqueueJob(frd->ctx, js_finrec_job, 2, args);
             }
             JS_FreeValueRT(rt, fre->token);
             js_free_rt(rt, fre);
```
Comment (bnoordhuis) [inline quickjs.c:53332]: This appears to cause #648 and now that I'm looking at it more closely, I believe a spot a bug:

If the branch is _not_ taken (i.e. no job is enqueued), shouldn't it `JS_FreeValueRT(rt, fre->held_val)`? `fre` is freed here.

Comment (saghul) [reply quickjs.c:53332]: Possibly yeah. The object might not be live so I think we need to check for that.

Comment (bnoordhuis) [reply quickjs.c:53332]: Figured it out just now: it **should** call `JS_FreeValueRT(rt, fre->held_val)` because JS_EnqueueJob increments the ref count, and js_finrec_job should **not** call `JS_FreeValue(ctx, argv[1])`. Pull request incoming.
