### PR TITLE
Fix Error.stackTraceLimit = Infinity

### LINKED ISSUE #858: Error.stackTraceLimit = Infinity results in empty stacktrace in errors.
```ts


console.log(new Error().stack); // Error stack is correct

Error.stackTraceLimit = Infinity;

console.log(new Error().stack); // Empty after setting `Error.stackTraceLimit`
```

### PR DESCRIPTION
**Pull request by ammarahm-ed**
Closes #858

### CODE REVIEW

File: quickjs.c [hunk 1]
```diff
@@ -38057,10 +38057,10 @@ static JSValue js_error_set_stackTraceLimit(JSContext *ctx, JSValue this_val, JS
 {
     if (JS_IsUndefined(this_val) || JS_IsNull(this_val))
         return JS_ThrowTypeErrorNotAnObject(ctx);
-    int limit;
-    if (JS_ToInt32(ctx, &limit, value) < 0)
+    double limit = 0;
+    if (JS_ToFloat64(ctx, &limit, value) < 0)
         return JS_EXCEPTION;
-    ctx->error_stack_trace_limit = limit;
+    ctx->error_stack_trace_limit = isinf(limit) ? INT_MAX : (int) limit;
```
Comment (saghul) [inline quickjs.c:38063]: Do we need to handle -Infinity?

Comment (ammarahm-ed) [reply quickjs.c:38063]: I don't think we do, it works without it.

**Comment by ammarahm-ed** [comment]
It seems that this works on mac but fails on Linux and Windows.

**Comment by saghul** [comment]
Yes it seems like you'll have to go back to explicitly testing for infinity.

**Comment by ammarahm-ed** [comment]
@saghul can you start the tests again

File: quickjs.c [hunk 2]
```diff
@@ -38057,10 +38057,10 @@ static JSValue js_error_set_stackTraceLimit(JSContext *ctx, JSValue this_val, JS
 {
     if (JS_IsUndefined(this_val) || JS_IsNull(this_val))
         return JS_ThrowTypeErrorNotAnObject(ctx);
-    int limit;
-    if (JS_ToInt32(ctx, &limit, value) < 0)
+    double limit = 0;
+    if (JS_ToFloat64(ctx, &limit, value) < 0)
         return JS_EXCEPTION;
-    ctx->error_stack_trace_limit = limit;
+    ctx->error_stack_trace_limit = isinf(limit) ? 2147483647 : limit;
```
Comment (bnoordhuis) [inline quickjs.c:38063]: Why not INT32_MAX?
```suggestion
    ctx->error_stack_trace_limit = isinf(limit) ? INT32_MAX : limit;
```
But you changed the conversion from JS_ToInt32 to JS_ToFloat64 and that means NaNs can also show up now.

Casting NaN to an integer is UB. The logic should probably be something like:
```suggestion
    ctx->error_stack_trace_limit = isfinite(limit) ? limit : INT32_MAX;
```

Comment (ammarahm-ed) [reply quickjs.c:38063]: I tried using `INT_MAX` but it was missing on Linux.

File: quickjs.c [hunk 3]
```diff
@@ -38057,10 +38057,10 @@ static JSValue js_error_set_stackTraceLimit(JSContext *ctx, JSValue this_val, JS
 {
     if (JS_IsUndefined(this_val) || JS_IsNull(this_val))
         return JS_ThrowTypeErrorNotAnObject(ctx);
-    int limit;
-    if (JS_ToInt32(ctx, &limit, value) < 0)
+    double limit = 0;
+    if (JS_ToFloat64(ctx, &limit, value) < 0)
         return JS_EXCEPTION;
-    ctx->error_stack_trace_limit = limit;
+    ctx->error_stack_trace_limit = isfinite(limit) ? limit : INT32_MAX;
```
Comment (saghul) [inline quickjs.c:38063]: I think you need to check for infinity and then for < 0 here. This test will fail now, and it shouldn't.

```
diff --git a/tests/bug858.js b/tests/bug858.js
index be66bd7..debc6b3 100644
--- a/tests/bug858.js
+++ b/tests/bug858.js
@@ -2,3 +2,7 @@ import {assert} from "./assert.js";
 
 Error.stackTraceLimit = Infinity;
 assert(new Error("error").stack.includes("bug858.js")); // stack should not be empty
+
+Error.stackTraceLimit = -Infinity;
+assert(!(new Error("error").stack.includes("bug858.js"))); // stack should be empty
+
```

v8 doesn't produce a stack trace in that case. Same goes for NaN. Let's add some tests for those as well please.

Comment (ammarahm-ed) [reply quickjs.c:38063]: Just tested now, the tests pass with NaN, Infinity, -Infinity. All these are not finite. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isFinite

Comment (saghul) [reply quickjs.c:38063]: How did you test? My diff against your PR is what fails for me.

File: quickjs.c (hunk 2 above)
Comment (bnoordhuis) [reply quickjs.c:38063]: It's INT32_MAX

File: tests/bug858.js [hunk 4]
```diff
@@ -0,0 +1,10 @@
+import {assert} from "./assert.js";
+
+Error.stackTraceLimit = Infinity;
+assert(new Error("error").stack.includes("bug858.js")); // stack should not be empty
+
+Error.stackTraceLimit = -Infinity;
+assert(new Error("error").stack.includes("bug858.js")); // stack should not be empty
```
Comment (saghul) [inline tests/bug858.js]: This and next are incorrect. There must be no stack trace. That's how V8 behaves. Have you observed otherwise?

**Comment by ammarahm-ed** [comment]
Hey @saghul I didn't look closely at your diff in review, fixed now and all tests now pass.

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
On a second thought, if we want to 100% mimic how v8 behaves we should store the JSValue and extract it when necessary.

Right now if you set it to -Infinity you'll get back 0, whereas Chrome gets you back the same value you set.

Thoughts @bnoordhuis ?

**Comment by bnoordhuis** [comment]
That means calling JS_ToFloat64, which can throw an exception, when we're already in an exception state. What is the expected behavior of this?
```js
Error.stackTraceLimit = {valueOf(){ throw "evil" }}
try{ throw new Error("fail") }
catch(e){ console.log(e) } // "fail" or "evil"?
```

**Comment by saghul** [comment]
I Node one gets "fail". We do save the previous exception not to clobber it, so it seems like we should be good to do that?

**Comment by bnoordhuis** [comment]
Yeah, that seems reasonable. Let's follow what node/chrome do then.

FWIW, I'm okay with landing this PR as-is and then one of us doing a follow-up fix-up.

**Comment by saghul** [comment]
Sounds good! I can work on it.
